#pragma once

// Stub of libui's ui/GraphicTypes.h for the OpenHarmony bringup build.
// Provides android::ui::Dataspace with values matching android_dataspace.

#include <stdint.h>

#include <system/graphics.h>

namespace android {
namespace ui {

// Unscoped enum so that bitwise operations with HAL_DATASPACE_* masks work,
// while still allowing Dataspace::TRANSFER_ST2084 style access.
enum Dataspace : int32_t {
    UNKNOWN = HAL_DATASPACE_UNKNOWN,

    STANDARD_MASK = HAL_DATASPACE_STANDARD_MASK,
    STANDARD_UNSPECIFIED = HAL_DATASPACE_STANDARD_UNSPECIFIED,
    STANDARD_BT709 = HAL_DATASPACE_STANDARD_BT709,
    STANDARD_BT2020 = HAL_DATASPACE_STANDARD_BT2020,
    STANDARD_DCI_P3 = HAL_DATASPACE_STANDARD_DCI_P3,
    STANDARD_ADOBE_RGB = HAL_DATASPACE_STANDARD_ADOBE_RGB,

    TRANSFER_MASK = HAL_DATASPACE_TRANSFER_MASK,
    TRANSFER_UNSPECIFIED = HAL_DATASPACE_TRANSFER_UNSPECIFIED,
    TRANSFER_LINEAR = HAL_DATASPACE_TRANSFER_LINEAR,
    TRANSFER_SRGB = HAL_DATASPACE_TRANSFER_SRGB,
    TRANSFER_SMPTE_170M = HAL_DATASPACE_TRANSFER_SMPTE_170M,
    TRANSFER_GAMMA2_2 = HAL_DATASPACE_TRANSFER_GAMMA2_2,
    TRANSFER_GAMMA2_6 = HAL_DATASPACE_TRANSFER_GAMMA2_6,
    TRANSFER_GAMMA2_8 = HAL_DATASPACE_TRANSFER_GAMMA2_8,
    TRANSFER_ST2084 = HAL_DATASPACE_TRANSFER_ST2084,
    TRANSFER_HLG = HAL_DATASPACE_TRANSFER_HLG,

    RANGE_MASK = HAL_DATASPACE_RANGE_MASK,
    RANGE_FULL = HAL_DATASPACE_RANGE_FULL,
    RANGE_LIMITED = HAL_DATASPACE_RANGE_LIMITED,
    RANGE_EXTENDED = HAL_DATASPACE_RANGE_EXTENDED,

    SRGB = HAL_DATASPACE_V0_SRGB,
    BT2020 = HAL_DATASPACE_BT2020,
    DISPLAY_P3 = HAL_DATASPACE_DISPLAY_P3,
};

}  // namespace ui
}  // namespace android
