#pragma once

#include <android/native_window.h>

enum {
    NATIVE_WINDOW_WIDTH = 0,
    NATIVE_WINDOW_HEIGHT = 1,
    NATIVE_WINDOW_FORMAT = 2,
    NATIVE_WINDOW_MIN_UNDEQUEUED_BUFFERS = 3,
    NATIVE_WINDOW_QUEUES_TO_WINDOW_COMPOSER = 4,
    NATIVE_WINDOW_CONCRETE_TYPE = 5,
    NATIVE_WINDOW_DEFAULT_WIDTH = 6,
    NATIVE_WINDOW_DEFAULT_HEIGHT = 7,
    NATIVE_WINDOW_TRANSFORM_HINT = 8,
    NATIVE_WINDOW_CONSUMER_RUNNING_BEHIND = 9,
    NATIVE_WINDOW_MAX_BUFFER_COUNT = 10,
};

enum {
    NATIVE_WINDOW_API_EGL = 1,
};

enum {
    NATIVE_WINDOW_SCALING_MODE_FREEZE = 0,
};

enum {
    NATIVE_WINDOW_TRANSFORM_FLIP_H = 0x01,
    NATIVE_WINDOW_TRANSFORM_FLIP_V = 0x02,
    NATIVE_WINDOW_TRANSFORM_ROT_90 = 0x04,
    NATIVE_WINDOW_TRANSFORM_ROT_180 = 0x03,
    NATIVE_WINDOW_TRANSFORM_ROT_270 = 0x07,
};

enum {
    ANATIVEWINDOW_TRANSFORM_IDENTITY = 0,
    ANATIVEWINDOW_TRANSFORM_MIRROR_HORIZONTAL = NATIVE_WINDOW_TRANSFORM_FLIP_H,
    ANATIVEWINDOW_TRANSFORM_MIRROR_VERTICAL = NATIVE_WINDOW_TRANSFORM_FLIP_V,
    ANATIVEWINDOW_TRANSFORM_ROTATE_90 = NATIVE_WINDOW_TRANSFORM_ROT_90,
    ANATIVEWINDOW_TRANSFORM_ROTATE_180 = NATIVE_WINDOW_TRANSFORM_ROT_180,
    ANATIVEWINDOW_TRANSFORM_ROTATE_270 = NATIVE_WINDOW_TRANSFORM_ROT_270,
};

enum {
    ANATIVEWINDOW_QUERY_MIN_UNDEQUEUED_BUFFERS = NATIVE_WINDOW_MIN_UNDEQUEUED_BUFFERS,
};

enum {
    ANATIVEWINDOW_PERFORM_SET_USAGE = 0,
    ANATIVEWINDOW_PERFORM_SET_USAGE64 = 1,
    ANATIVEWINDOW_PERFORM_SET_BUFFERS_GEOMETRY = 2,
    ANATIVEWINDOW_PERFORM_SET_BUFFERS_FORMAT = 3,
    NATIVE_WINDOW_SET_BUFFER_COUNT = 4,
};

static inline int native_window_api_connect(ANativeWindow*, int) { return 0; }
static inline int native_window_api_disconnect(ANativeWindow*, int) { return 0; }
static inline int native_window_set_scaling_mode(ANativeWindow*, int) { return 0; }
